name: Ingest pipeline for create update channel info

on:
  schedule:
  - cron: "0 0/12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: create env file
      run: |
        touch .env
        echo FULL_ACCESS_RESTDB_API_KEY =${{ secrets.FULL_ACCESS_RESTDB_API_KEY }} >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run ingest --if-present
